### ISSUE TITLE
(CSS) element in @supports highlighted incorrectly

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#1067]
It only occurs on elements, and only when the element isn't preceded by white-space (on the same line).

![1](https://user-images.githubusercontent.com/1097609/27843192-657ab44c-6111-11e7-816f-1f05790ae37c.png)

**Comment by pdknsk** [comment]
I think *element* may be the wrong terminology here. I mean *tags* basically.

**Comment by keith-hall** [comment]
Looks like all that needs to be done to fix this is to remove this line: https://github.com/sublimehq/Packages/blob/8ea911b505e73c09c02f3b07a31ff0773845493b/CSS/CSS.sublime-syntax#L387

**Comment by philipbordallo** [comment]
Copying the css from the image, just to make it easier to work with:
```css
@supports (display: grid) {span{display: grid}}

@supports (display: grid) {
span {display:grid}
}

@supports (display: grid) {.span{display: grid}}

@supports (display: grid) {
.span {display:grid}
}

@supports (display: grid) {
  span {display:grid}
}
```
