### ISSUE TITLE
[Feature Request] Push count/switching in syntax files

### ISSUE THREAD

**Issue by borela** [sublimehq/Packages#1291]
Consider a highlighted JSON file:

```json
{
  "level1": {
    "level2": {
      "level3": {
      }
    }
  }
}
```

The current approach used by the repo to detect the level is stacking the meta scopes, however that's not designer friendly, [so I worked arround it](https://github.com/borela/naomi/blob/master/syntaxes/json1/literal/object/level-1.sublime-syntax) and gave the tokens scopes like `level-1.json level-a.json.json1` , `level-2.json level-b.json.json1` , etc... where each level has a scope with a number and an alternating scope `a` and `b` which gives the option to either give each level a unique color or just alternate them.

If I could somehow know the push level and concatenate it into the scope, the syntax would be simpler, for example:

```yaml
contexts:
  main:
    - match: {
      scope: level-{{Current-Level}}.json
      push: main
   # Or for alternating levels.
    - match: {
      scope: level-{{Current-Letter}}.json
      push: main
```

The added benefit of having something like this is in languages with too many parenthesis like Lisp, you could easily add a scope that indicates the level or alternating color directly in the syntax without having to use another plugin.
