### ISSUE TITLE
[HTML] Whitespace breaks tags and attributes.

### ISSUE THREAD

**Issue by Thom1729** [sublimehq/Packages#1305]
```
<div title
    ="foo"></div>
//  ^ punctuation.separator.key-value
//   ^^^^^ string

<
    div></div>
//  ^^^^ meta.tag

<script
    type="text/notjavascript">
        
    42
//  ^^ - source.js
</script>
```

I ran into these bugs while trying to write an extended HTML syntax for Vue.js (https://github.com/vuejs/vue-syntax-highlight/issues/108). Fixing them will make that task much easier.

The solution to these is probably to use the stack more. The old:

```yaml
tag-generic-attribute:
  - match: '(?:^|\s+)(([a-zA-Z0-9:_.-]+)\s*(=)\s*)'
    captures:
      1: meta.attribute-with-value.html
      2: entity.other.attribute-name.html
      3: punctuation.separator.key-value.html
    push: # <snip>
  - match: '([a-zA-Z0-9:\-_.]+)'
    captures:
      1: entity.other.attribute-name.html
```

The new:

```yaml
tag-generic-attribute:
  - match: '\b[a-zA-Z0-9:_.-]+\b'
    scope: entity.other.attribute-name.html
    push:
      - meta-attribute
      - expect-attribute-equals

meta-attribute:
  - meta_scope: meta.attribute.html
  - match: ''
    pop: true

expect-attribute-equals:
  - match: '='
    scope: punctuation.separator.key-value.html
    set: expect-attribute-value
  - match: (?=\s*(?!=))
    pop: true

expect-attribute-value: # <snip>
```
