### ISSUE TITLE
[CSS] Comments inside calc clause not detected

### ISSUE THREAD

**Issue by contacreast** [sublimehq/Packages#1776]
```css
a{
  height:calc(10px/*);
  font-family:"a*/);
}
```

![](https://user-images.githubusercontent.com/45112259/49185090-48967f80-f361-11e8-9bf8-9d32fbced6b2.png)

<sub>Quick advice: don't waste time reading the spec, this is valid syntax, confirmed.</sub>
