### ISSUE TITLE
[HTML] embedded code in tag-names valueable?

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1788]
Is it of any value to enable cgi tags within html tags? Something like the following?

Just wonder about it as I found this not being highlighted correctly in the current php syntax. 
```php
  <tag<?php $bar ?>na<?php $baz ?>me att<?php $bar ?>rib=false />
//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ meta.tag.other.html
//^ punctuation.definition.tag.begin.html
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ entity.name.tag.other.html
//    ^^^^^ punctuation.section.embedded.begin.php
//    ^^^^^^^^^^^^^ meta.embedded.line.php
//               ^^ punctuation.section.embedded.end
//                   ^^^^^ punctuation.section.embedded.begin.php
//                   ^^^^^^^^^^^^^ meta.embedded.line.php
//                              ^^ punctuation.section.embedded.end
//                                   ^^^^^^^^^^^^^^^^^^^^^^^^^ meta.attribute-with-value.html
//                                   ^^^^^^^^^^^^^^^^^^^ entity.other.attribute-name.html
//                                      ^^^^^ punctuation.section.embedded.begin.php
//                                      ^^^^^^^^^^^^^ meta.embedded.line.php
//                                                 ^^ punctuation.section.embedded.end
//                                                             ^^ punctuation.definition.tag.end.html
```

To fix it, we'd need to change the tag matching logic in HTML the same way it is handled with `tag-generic-attribute`.

```YAML
  tag-other:
    - match: </?(?=[A-Za-z])
      scope: punctuation.definition.tag.begin.html
      push:
        - tag-other-body
        - tag-other-name

  tag-other-name:
      - meta_content_scope: entity.name.tag.other.html
      - match: '{{tag_name_break}}'
        pop: true

  tag-other-body:
      - meta_scope: meta.tag.other.html
      - include: tag-end-maybe-self-closing
      - include: tag-attributes
```

While it fixes the php tag the additional lookahead and push/pop required to do it, has a relevant impact on performance. My performance test page with about 100k lines of code increased from 1.5 to 2.3 seconds doing the required change.
