### ISSUE TITLE
[JavaScript] HTML and CSS syntax highlighting in tagged template strings

### ISSUE THREAD

**Issue by jrburke** [sublimehq/Packages#179]
Is it possible to support HTML/CSS syntax highlighting inside a tagged template string? I am looking to do the equivalent of [this atom editor change](https://github.com/atom/language-javascript/pull/282).

My first attempt at this did not work out so well. I just tried modifying the existing literal-quasi (but locally renamed it to literal-template-string everywhere in the file), just to see if I could get the HTML referencing correctly, before creating a new kind of match just for the "ending in html" tagged template function case:

``` yaml
  literal-template-string:
    - match: '([a-zA-Z$_][\w$_]*)?(`)'
      captures:
        1: entity.template-string.tag.name.js
        2: punctuation.definition.template-string.begin.js
      push:
        - meta_content_scope: source.html.embedded.js
        - include: 'scope:text.html.basic'
      with_prototype:
        - match: "`"
          captures:
            0: punctuation.definition.template-string.end.js
          pop: true
        - match: '\${'
          captures:
            0: punctuation.template-string.element.begin.js
          push:
            - meta_scope: entity.template-string.element.js
            - match: "}"
              captures:
                0: punctuation.template-string.element.end.js
              pop: true
            - include: expression
```

But I get an `Apparent recursion within a with_prototype action: 25000 context sanity limit hit` error. I am very new to these kinds of syntax files, so I expect I am making some very simple mistakes. I appreciate receiving any pointers on how to fix the issue.

My guess is that since JavaScript.sublime-syntax's `expression` has `include: literal-template-string` and `literal-template-string` is referencing `source:text.html.basic`, which inside of it references `scope:source.js`, maybe some pathway with all of that is causing the recursion.

Related context:
- This does not take into account the changes in #165, I expect to redo some of it once that changeset lands.
- Previous discussion in Benvie/JavaScriptNext.tmLanguage#134, but I would want to scope the use of HTML to tagged template functions ending in `(?i)html`, to allow alternate highlighting for other content, like CSS for functions ending in `(?i)css`, as the Atom changeset does.
- GitHub's source display now does this kind of higlighting: [example test.js](https://github.com/jrburke/tts-syntax-highlight/blob/master/test.js).
- That test file is part of a [tts-syntax-highlight repo](https://github.com/jrburke/tts-syntax-highlight) to track this sort of enhancement in editors now that ES2015 template strings are used more.

**Comment by orizens** [comment]
There's also a suggested YML solution in this thread 
https://forum.sublimetext.com/t/javascript-es6-template-literals-syntax-for-html/18242

**Comment by Rayraegah** [comment]
I made it work by extending the default JavaScript Syntax. 

![image](https://cloud.githubusercontent.com/assets/1559650/19476664/49869248-9532-11e6-924b-4213edc13536.png)


```

%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
name: JavaScript Custom Element
file_extensions:
  - element.js
  - tag.js
scope: source.js.tag
contexts:
  main:
    - match: ""
      push: Packages/JavaScript/JavaScript.sublime-syntax
      with_prototype:
      - match: '`\n'
        push:
          - meta_content_scope: text.html.basic.embedded.js
          - include: 'scope:text.html.basic'
          - match: '`'
            pop: true
          - match: '\$\{'
            captures:
              0: punctuation.definition.template-expression.begin.js
            push:
              - meta_scope: meta.template.expression.js
              - meta_content_scope: source.js.embedded.expression
              - match: '\}'
                scope: punctuation.definition.template-expression.end.js
                pop: true


```

**Comment by ericmcdaniel** [comment]
@Rayraegah Your solution doesn't work with tagged template literals.

I replaced `- match: '`\n'` with `- match: '([a-zA-Z$_][\w$_]*)?(`)'` and it worked.

**Comment by qodesmith** [comment]
@Rayraegah where did you save that file and with what name?

**Comment by Rayraegah** [comment]
@qodesmith Just create a new syntax file and dump that code in there. Also, use @ericmcdaniel 's suggestion.

Then, in your editor settings, set open all files with the new syntax instead of the default.

**Comment by skylize** [comment]
> @Rayraegah where did you save that file and with what name?

> @qodesmith Just create a new syntax file and dump that code in there.

Ummm....  So where did you save that file and with what name?

**Comment by Thom1729** [comment]
The [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom/) package lets you add [user-defined template tags](https://github.com/Thom1729/Sublime-JS-Custom/#custom_tagged_literals-object). In my opinion, this is a better approach than adding them to the core syntax.

**Comment by Slakinov** [comment]
@Thom1729 would you mind explaining in a bit more detail how the JS Custom package should be set up to show html syntax within `` backticks in JS files?

![screen shot 2018-05-09 at 13 16 56](https://user-images.githubusercontent.com/3966178/39814204-55c9df42-538b-11e8-97b8-0e25cdeb44b3.png)

**Comment by Slakinov** [comment]
@Thom1729 Thanks for the info! Just updated the package and tried that config.
I'm now getting the recursion warning someone mentioned above.
Any idea how to fix?
Do I need to make an alternative html syntax definition that doesn't attempt to parse js again within itself?
Sorry if these are dumb questions.
![screen shot 2018-05-09 at 19 24 01](https://user-images.githubusercontent.com/3966178/39832386-ed7afb72-53be-11e8-9583-0ddbafb4a2f7.png)

**Comment by Thom1729** [comment]
Are you running Sublime 3.1? The new version of the core HTML syntax uses `embed`/`escape` instead of `push`/`with_prototype`, and that should avoid the infinite recursion.

**Comment by Slakinov** [comment]
I'm running build 3170, which is 3.1 according to the sublime site, but 3.0 in my about window.

Had to remove some user package files after removing the JS Custom package to stop the recursion error when viewing any .html file.

I've now reinstalled JS Custom, and added your config above, no recursion error now, but no backtick highlighting either...

Any more ideas?

![screen shot 2018-05-10 at 10 54 31](https://user-images.githubusercontent.com/3966178/39864130-99c379be-5440-11e8-98c9-fa6afe03913e.png)

**Comment by keith-hall** [comment]
my guess is you need to write `html` before the opening backtick.

**Comment by Thom1729** [comment]
Yes, you'd need to write:

```js
template: html`
    <div class="playlist">...</div>
`
```

The JS Custom extension isn't designed to apply arbitrary highlighting to regular, untagged templates. You probably wouldn't want *all* template strings to be highlighted as HTML, because template strings are used for many purposes.

However, there may be an opportunity for extension here. The [Ecmascript Sublime](https://github.com/bathos/Ecmascript-Sublime) lets you specify a syntax in a comment, like so:

```js
template: /* syntax: html */ `
    <div class="playlist">...</div>
`
```

A similar feature might be useful for JS Custom. Of course, like `custom_template_tags`, the feature would be fully configurable. Would this be useful to you?

**Comment by Slakinov** [comment]
Hmm. This isn't straightforward is it :(
Putting html before a backtick makes the JS invalid, Vue can't execute it.

**Comment by Slakinov** [comment]
I personally would find a syntax highlighter that assumes all backtick blocks in JS to contain html, since I never use them for anything else in JS files.

**Comment by kleinfreund** [comment]
> Putting html before a backtick makes the JS invalid

That’s not correct. Those are called _tagged_ [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

> I personally would find a syntax highlighter that assumes all backtick blocks in JS to contain html, since I never use them for anything else in JS files.

You might not use them for anything others, but a lot of people use them for anything but not HTML. The default should definitely be no extra highlighting.

**Comment by Slakinov** [comment]
I'm not saying this should be default JS highlighting at all, I'm just trying to get a solution to work for my own case, and would imagine other people would want this behaviour as an option, too.

Haven't tried running my code through Babel in this case, but Chrome throws an error with tagged template literals:
![screen shot 2018-05-15 at 14 12 33](https://user-images.githubusercontent.com/3966178/40058789-1fcbc18a-584a-11e8-900f-ed5743838ab1.png)

**Comment by Slakinov** [comment]
Aha! That works :)

**Comment by Slakinov** [comment]
...And now the recursion errors are back when reopening Sublime 😭  
Regular HTML syntax highlighting appears to be hosed.

Sublime build 3176
Latest JSCustom, with the settings suggested above
Have tried 'rebuild syntaxes'

![screen shot 2018-05-15 at 15 02 33](https://user-images.githubusercontent.com/3966178/40061787-9d6f044c-5851-11e8-801b-b19ad9f05697.png)

**Comment by Slakinov** [comment]
https://github.com/bathos/Ecmascript-Sublime works great, I can live with those syntax declaration comments

**Comment by Thom1729** [comment]
I've figured it out.

The underlying problem is that the HTML syntax is embedding the `source.js` scope, while the JS Custom syntax is embedding the HTML syntax using `with_prototype`. This is causing the recursion error. I had thought that if at least one of those two syntaxes used `embed`, then it would work. Apparently, I was wrong.

Ecmascript-Sublime works around this by accident. Because of the way that syntax is written, the HTML syntax won't embed it; it will embed another JavaScript syntax instead, such as the core syntax. This means that you can't use any of Ecmascript-Sublime's features in embedded JavaScript, and so the error never comes up.

The HTML syntax *will* embed JS Custom syntaxes, though. Specifically, it will embed the syntax for the last configuration in lexicographic order. If that syntax embeds HTML using `with_prototype`, the error you've found will occur. I couldn't reproduce the error because the configuration I was testing all of this on was not the last one in lexicographic order.

I plan to solve this in a systematic manner. However, there is a simple workaround that will solve the problem for you today. Add the following configuration to your `JS Custom.sublime-settings`:

```json
        "~default": {
            "hidden": true,
            "custom_template_tags": null,
        },
```

This will create a new, hidden syntax that will be used by the HTML syntax and other syntaxes for embedded JavaScript. It will use all of your default settings, except that it won't use any custom template tags. This should eliminate those recursion errors once and for all.

Sorry that this ended up being a hassle!

**Comment by Slakinov** [comment]
Super-delayed thanks for that last post :)
Have been using JS Custom with these settings for months, working perfectly for my needs.
Just posting here for reference:
![screen shot 2018-08-23 at 13 43 09](https://user-images.githubusercontent.com/3966178/44526133-f21f0280-a6da-11e8-87ca-e400d8afca38.png)

**Comment by niksy** [comment]
@Rayraegah your suggestion doesn’t seem to be working properly when you have JS inside template literal. Is this up to date?

**Comment by Rayraegah** [comment]
@niksy I didn't have a case where I had to handle JS inside a template literal. I did try the edge case

Can you check with the following line uncommented?

```
            push:
              - meta_scope: meta.template.expression.js
              - include: 'scope:source.js'
              #- meta_content_scope: source.js.embedded.expression
              - match: '\}'
                scope: punctuation.definition.template-expression.end.js
                pop: true
```
