### ISSUE TITLE
[RFC] Templating/interpolation scopes

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#1875]
Currently for templating/interpolation inside of strings we use a whole bunch of different scopes. I'd like to collect opinions about what we should standardize on, and a list of syntaxes we need to address. Here are a few to start.

## Python

Python has f strings, such as:

```python
f'This is a and { var + var2 }'
``` 

The leading `f` clearly indicates the string is an fstring.

The entire string gets `meta.string.interpolated.python`. The non-interpolated parts have `string.quoted.single.python`. The interpolated parts get `meta.interpolation.python`. The punctuation is `punctuation.section.interpolation.*.python` and everything between the punctuation is `source.python.embedded`.
 
## JavaScript

JS has template strings in the form:

```js
tag`This is a string and ${ var1 + var2 }`
```

The tag and backtick clearly indicate the string is a template.

The string gets `string.template.js`, it is removed for the expression parts. The expression including punctuation gets `meta.template.expression.js`. The open/close punctuation gets `punctuation.definition.template-expression.*.js`. Inside of the punctuation there is `source.js.embedded.expression`.

## PHP

PHP supports both variable and expression interpolation. Double-quoted string and heredocs can have interpolation, whereas single-quoted can't.

### Variables

Variables can be interpolated in the following ways:

```php
"$var1 or $var2->member or $var3[key]"
```

Each of these get the scopes the same would get outside of a string, but they are just layered on top of the `string.quoted.double.php` scope that is applied to the entire string. Strings in PHP get `meta.string-contents.quoted.double.php` for everything between the quotes.

### Expressions

In addition to basic variable interpolation, full expressions can be used.

```php
"This is a string and { $var1 + $var2 }"
```

Currently the `string.quoted.double.php` is not removed for the expression. The punctuation gets `punctuation.definition.expression.php`. All other syntax is scoped verbatim to the same constructs outside of string interpolation.

## Ruby

Ruby supports string interpolation of expressions via:

```ruby
"This is a string and #{var1 + var2}"
```

This can be used in double-quoted string, but not single-quoted strings. There is no leading indicator that the string is for the purpose of templating/interpolation.

The string is `string.quoted.double.ruby`, which is removed for the interpolated section. The interpolation gets `meta.interpolation` (no `.ruby`). The punctuation gets `punctuation.section.interpolation.*.ruby`. Between the punctuation is `source.ruby.embedded`.

**Comment by wbond** [comment]
## Go

Go has the template module. It doesn't allow arbitrary go, but a limited number of functions, some formatting operators (sort of like the Python `format()` method), and item access via `.FieldName`.

There is no indication at the beginning of the string it will be a template. They may be used in double-quoted or raw strings.

```go
"{{.FieldName}} is interpolated"
```

A more complex example:

```go
"{{with $x := "output" | printf "%q"}}{{$x}}{{end}}"
```

I am working on merging in a PR with this right now. Based on Python and Ruby, I am probably going to use similar scopes for now, and we can tweak when we agree on what should be used moving forward.

**Comment by wbond** [comment]
Would love input from @FichteFoll, @deathaxe, @keith-hall, @Thom1729, @mitranim, @djspiewak, @michaelblyons, @randy3k, @gwenzek, @rwols, or anyone else who would like to weigh in.

**Comment by FichteFoll** [comment]
As the author of the interpolation highlighting in Python's f-string, I'd like to say that I am still very much in favor of this scheme because of the following reasons:

1. It uses general scope names with "interpolation" instead of "template" like in JS.
2. Non-string parts (i.e. the interpolation) should *not* have a string scope applied. However, in order to still get a grasp on the extend of such an interpolated string a meta scope was added in `meta.string.interpolated`. Plugins such as BracketHighlighter benefit from and rely on this.

This solves all issues for Python, but there are issues with other languages not addressed by the convention used.

1. PHP and ShellScript can interpolate variables in string just through a `$varame` reference. The variables are *not* literal strings and instead interpolated, so should the string scope be popped for these? See also https://github.com/SublimeTextIssues/Core/issues/2546#issuecomment-461515161.
2. I don't really get what's going on with Go's templates from just looking at this example here.

**Comment by wbond** [comment]
@FichteFoll Go's template module is probably closer to a Python `format()` or super-lightweight mustache.

**Comment by keith-hall** [comment]
I like the idea of standardizing, and I agree with @FichteFoll about the generic `interpolation` subscope being more uniform than `template` and that clearing the `string` scope (but not the meta scope) makes sense for the interpolated contents. I believe the punctuation denoting the interpolation start and end (where they exist) should have the `string` scope but not the `source.ext.embedded` scope, and only the actual interpolated contents should get the embedded source scope. Also, some languages/constructs allow newlines in the interpolated code and some don't. I believe we generally try to use `punctuation.section` (as opposed to `punctuation.definition` which is being used in the JS syntax atm) where larger blocks of code can be used, so I guess we would standardize on that for simplicity rather than decide to use `definition` where only single line code is allowed etc.
In may also be worth outlining and discussing which languages support formatting as part of the interpolation syntax, and what scopes to use there.

For PHP, I vote for removing the string scope where variables and expressions appear for uniformity and clarity - many color schemes don't highlight variables differently, and thus they are harder to spot with the string scope still applied.

Hopefully what I have written is readable and understandable, forgive me if not, typing on mobile atm.

**Comment by Thom1729** [comment]
I agree that we should standardize these scopes and update the core syntaxes accordingly. I don't have a strong opinion as to which scopes we should use, although the Python ones look good at a glance.

# Moving parts

The following scopes are likely to be relevant to string interpolation:

- The “exterior” `meta` scope.
- The “interior” `string` scope.
- “Tag” punctuation.
- The open/close quotes.
- Punctuation/brackets demarcating interpolations.
- Interpolated expressions/variable names.
- Formatting specifiers.

# String properties

In Python, and in several other languages, a string may have several orthogonal characteristics. For instance, a Python string may be:

- Single or double-quoted.
- Inline or block.
- Raw (`r`).
- Interpolated (`f`).
- Unicode (`u`).
- Bytes (`b`).

This is all information that could be useful for highlighting or for simple plugin features. A lot of this isn't standardized among the core syntaxes. But the larger problem is that it's hard to write a selector to handle these: if the string `rb"foo!"` is scoped `string.quoted.double.raw.bytes`, then you can't select it with something like `string.raw` or `string.bytes`. The more information we represent under the `string` scope, the less practical it is to do anything with it.

The solution here would be to extend the selector syntax. Something like `string.quoted...raw` could match the above scope. Ideally, `string.quoted...bytes...raw` would match as well, even though `raw` comes before `bytes` in the scope. This feature would be invaluable for woking with orthogonal features of all sorts. For instance, in JavaScript, a function might be a method, a generator, and/or async.

**Comment by deathaxe** [comment]
Also agree with such a standard. The following ideas came to my mind, while reading all your comments:

1. If the `string` scope is to be cleared for either simple variable interpolation or complex expression interpolation, we need a general `meta.string` scope to enable plugins to keep track of still being within a string.
2. I wonder whether it is important to distinguish normal strings from those which support interpolation via `meta.string.interpolated` or if it is just enough to have a general `meta.string` and just stack `meta.interpolation` as soon as the normal `string` is cleared. It would help with syntaxes which do not explicitely mark interpolated strings.
3. Instead of stacking, we could also clear both `meta.string string.quoted.double` and apply `meta.string.interpolation` within interpolation parts. _This would keep all the boundaries intact while minimizing the number of stacked scopes._

Here is a minimal example to illustrate my idea.

**String Interpolated.sublime-syntax**

```YAML
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
file_extensions:
  - php
scope: source.php

contexts:

  main:
    - include: strings
    - include: operators
    - include: variables

  operators:
    - match: '[-+*/]'
      scope: keyword.operator.php
    - match: '<<'
      scope: keyword.operator.php

  variables:
    - match: (\$)\w+\b
      scope: variable.other.php
      captures:
        1: punctuation.definition.variable.php

  strings:
    - match: '"'
      scope: punctuation.definition.string.begin.php
      push:
        - meta_include_prototype: false
        - meta_scope: meta.string.php string.quoted.double.php
        - match: \\.
          scope: constant.character.escape.php
        - match: '"'
          scope: punctuation.definition.string.end.php
          pop: true
        - include: interpolation
    - match: \'
      scope: punctuation.definition.string.begin.php
      push:
        - meta_include_prototype: false
        - meta_scope: meta.string.php string.quoted.single.php
        - match: \'
          scope: punctuation.definition.string.end.php
          pop: true

  interpolation:
    - match: \{
      scope: punctuation.definition.string.interpolation.begin.php
      push:
        - clear_scopes: 2
        - meta_scope: meta.string.interpolation.php
        - match: \}
          scope: punctuation.definition.string.interpolation.end.php
          pop: true
        - include: main
    - match: \$(?=\w+\b)
      scope: punctuation.definition.variable.php
      push:
        - clear_scopes: 2
        - meta_scope: meta.string.interpolation.php variable.other.php
        - match: (?=\s)
          pop: true
```

**Test Cases**

```
#SYNTAX TEST: "String Interpolated.sublime-syntax"

    "This $is my { 'inter' + $pol << "ated" } string."
#   ^ punctuation.definition.string.begin.php
#   ^^^^^^ meta.string.php string.quoted.double
#         ^^^ meta.string.interpolation.php - string.quoted.double
#            ^^^^ meta.string.php string.quoted.double
#                ^ punctuation.definition.string.interpolation.begin.php
#                ^^^^^^^^^^^^^^^^^^^^ meta.string.interpolation.php - string.quoted.double
#                                    ^^^^^^ meta.string.interpolation.php meta.string.php string.quoted.double
#                                          ^^ meta.string.interpolation.php - string.quoted.double
#                                           ^ punctuation.definition.string.interpolation.end.php
#                                            ^^^^^^^^^ meta.string.php string.quoted.double
#                                                    ^ punctuation.definition.string.end.php
```
