### ISSUE TITLE
Lua new syntax suggestion - too many things are highlighted as variables currently

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimehq/Packages#1899]
I fixed this for myself with this change:

```
  variable:
    - match: '{{identifier}}{{function_assignment_ahead}}'
      scope: entity.name.function.lua
      pop: true

    - match: '{{identifier}}{{function_call_ahead}}'
      scope: variable.function.lua
      pop: true

    - match: '{{identifier}}'
      scope: meta.property.lua
      pop: true
```

The scope in the third item is by default `variable.other.lua`. This way most text is defaulted to the normal color, and actual function names are much more easily distinguished (behavior is also more similar to the LuaExtended).
