### ISSUE TITLE
[CSS] Symbol Index includes Leading Whitespace

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#2057]
The selector for Goto Symbol in a CSS file is `meta.selector`, which appears to be matching leading whitespace before the start of a selector.

Test case:

```
        body {
            font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial;
            background-color: #f6f6f6;
            text-align: center;
        }
        h1 {
            margin-top: 100px;
            font-size: 4.0em;
            color: #333;
        }
```

**Comment by michaelblyons** [comment]
FWIW, I _think_ the reason it does that is to make sure that `,`-separated selectors are grouped together into the same `meta` scope. A fix should either maintain that or make an argument why it shouldn't be that way.

Test cases:

``` css
        h1, h2 {
            margin-top: 100px;
            font-size: 4.0em;
            color: #333;
        }
        h1 , h2 {
            margin-top: 100px;
            font-size: 4.0em;
            color: #333;
        }
        h1,
        h2 {
            margin-top: 100px;
            font-size: 4.0em;
            color: #333;
        }
```
