### ISSUE TITLE
[Lua] End of line is not considered as a part of the comment

### ISSUE THREAD

**Issue by 20Tauri** [sublimehq/Packages#2127]
With Lua syntax, on a comment line, the end of line is not considered as a part of the comment.
Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> before and after the last character to see this uncommon behavior.

Was: `source.lua`
Expected: `source.lua comment.line.lua`

A possible fix, is simply to addd `\n?` at the regexp

```yaml
    - match: (--).*\n?
      scope: comment.line.lua
      captures:
        1: punctuation.definition.comment.lua
```
