### ISSUE TITLE
[ShellScript] The `allow-end-of-options-token` setting in auto-generated builtin syntax has no effect

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#2311]
- Sublime Version: 4068
- OS Version: Windows 10

```bash

shift 1 -- -nooption
```

**Expected behavior**

The `--` is not supported by the `shift` command and should therefore not be highlighted.

**Actual behavior**

By including the `scope:source.shell.bash#cmd-args-boilerplate` the `allow-end-of-options-token` machinary seems not to have any effect atm, bacause `cmd-args-boilerplate` contains a rule to match the `--` token.

```yaml
  cmd-args-boilerplate:
    - match: (?={{is_end_of_interpolation}})
      pop: true
    - include: cmd-args-common
    - match: (?:\s+|^)--(?=\s|$)   ; <--- always applies to all commands and all builtins!
      scope: keyword.operator.end-of-options.shell
      set:
        - meta_content_scope: meta.function-call.arguments.shell
        - include: end-of-options-common
```

**Solutions**

1. We could either remove `allow-end-of-options-token` and the included contexts, so the `--` keeps highlighted as a general end-of-options tokens even if a command doesn't need/supports it.

2. We could tweak the contexts in a way which makes `--` being highlighted only if supported by a command, which seems to be the intended behavior.
