### ISSUE TITLE
[CSS] box-shadow multiple values

### ISSUE THREAD

**Issue by sineway** [sublimehq/Packages#2369]
It seems, the second value of the `box-shadow` property is not highlighted as it should:

![Screenshot from 2020-05-24 08-46-18](https://user-images.githubusercontent.com/23264894/82746675-21284380-9d9b-11ea-85cd-bcc3b5bb6cfb.png)

GitHub highlight:
``` css
.text-field__input:invalid:focus {
    box-shadow: 0 0 0 .125rem hsl(var(--red-50)) inset,
                0 0 0 .1875rem hsl(var(--red-50), .3);
}
```
- Sublime Version: 3.2.2, Build 3211
- OS: Arch Linux (GNOME 3.36.2)
