### ISSUE TITLE
[CSS] Counter Identifiers with Numbers Show as Multiple Tokens

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#2431]
- Sublime Version: 4079
- OS Version: macOS 10.15.6

```css
ul > li:first-child
{
    counter-reset: counter1;
}
```

The entirety of `counter1` should be a single token. With CSS it shows as two, one being `counter` and the second being `1`, which is currently scoped as a number.

There are a handful of places these identifiers are valid: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters.
