### ISSUE TITLE
[CSS] negative margin values marked as invalid

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2652]
- Sublime Version: 4094
- OS Version:

```css
.foo {
  margin: 0 -0.5rem 0.5rem -0.5rem;
}
```

![Screenshot 2020-12-12 at 20 38 08](https://user-images.githubusercontent.com/153197/101993328-f3b0d200-3cb9-11eb-934b-3a94374ccb6d.png)
