### ISSUE TITLE
[CSS] support latest gap which replaces grid-gap

### ISSUE THREAD

**Issue by princemaple** [sublimehq/Packages#2704]
- Sublime Version: 4095
- OS Version: Windows 10 19042

```css
.flex-or-grid {
  gap: 1em;
}
```

![image](https://user-images.githubusercontent.com/1329716/106073204-b4e9b500-615d-11eb-9da9-7a1623f4e114.png)
