### ISSUE TITLE
[YAML] Adding `{` can create a paired `}` in a weird place

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#2749]
- Sublime Version: 3.2 - 4098
- OS Version: MacOS Catalina 10.15.7

## Expected behavior

Typing `{` makes a paired `}` right after it.

## Actual behavior

Typing `{` makes a paired `}` several lines below. I'd be okay with not having auto-pairing at all, but the right kind of pairing is preferable.

## Steps to reproduce

1. Start with this YAML:
    ```yaml
    main:
      comments:
        - match: (^[ \t]+)?(--)
          captures:
            1: punctuation.whitespace.comment.leading.pascal
            2: punctuation.definition.comment.pascal
          push:
            - meta_scope: comment.line.double-dash.pascal.one
            - match: \n
              pop: true
    ```
2. At the end of either of the `- match` lines, type `{`.
3. See the matching `}` at the bottom of the file, indented to the level of the `- match` you chose.
