### ISSUE TITLE
[C++] Scope definition for enums in C++.sublime_syntax erroneously scoped as union

### ISSUE THREAD

**Issue by bexsella** [sublimehq/Packages#2864]
- Sublime Version: 4107
- OS Version: N/A

When writing a new colour scheme with C++ in mind specifically, I managed to find on line  [1152 of C++.sublime_syntax ](https://github.com/sublimehq/Packages/blob/f996a6fa9dcbda126d1e92a6bd47fe2be7892f63/C%2B%2B/C%2B%2B.sublime-syntax#L1152) is (potentially) erroneously scoped as `keyword.declaration.union.type.c++` instead of `keyword.declaration.enum.type.c++` see below:

```YAML
- match: '\benum(\s+(class|struct))?\b'
  scope: keyword.declaration.union.type.c++
  set: data-structures-enum-definition
```

If this is expected, disregard this issue.
