### ISSUE TITLE
[TypeScript] Can't match triple slash directives in the Typescript

### ISSUE THREAD

**Issue by jingyuexing** [sublimehq/Packages#2880]
- Sublime Version: 4100
- OS Version: win 10

``` typescript
/// <reference path="..." />
/// <reference path="..." />
```
before
![图片](https://user-images.githubusercontent.com/19589872/122973961-5ea73800-d3c4-11eb-88f3-01a67ab5d25f.png)
after:
![图片](https://user-images.githubusercontent.com/19589872/122974015-6ebf1780-d3c4-11eb-9739-38e1f7605a6e.png)

```yaml
ts-triple-slash-directives:
    - match: '///'
      scope: punctuation.definition.comment.ts
      push:
        - include: Packages/XML/XML.sublime-syntax#tag
        - match: $
          pop: true
```
