### ISSUE TITLE
[Haskell] multi-line string match 

### ISSUE THREAD

**Issue by absop** [sublimehq/Packages#2918]
- Sublime Version: 4112
- OS Version: Windows 10

``` haskell
testString = "This is a\
             \multi-line string literal\
             \example"
```

![image](https://user-images.githubusercontent.com/32818900/127240499-8dbc101f-3a24-4300-9a43-8ecc0af7889b.png)

The modification below could solve this problem
```YAML
        - match: \\\s
          captures:
            constant.character.escape.begin.haskell
          push:
            - match: \\
              captures:
                constant.character.escape.end.haskell
              pop: true
```
![image](https://user-images.githubusercontent.com/32818900/127240809-d5a7ef69-9993-4eba-ad04-adbd28e422b9.png)

After Modifiying
![image](https://user-images.githubusercontent.com/32818900/127240724-0142f450-0f45-4307-9988-c52c04617c5a.png)
