### ISSUE TITLE
[D] Add spacial scope for builtint types

### ISSUE THREAD

**Issue by RUSshy** [sublimehq/Packages#2977]
- Sublime Version: ST4 4113
- OS Version: Win10 x64

``` D
struct MyType {}

MyType my_type;
int builtin_type; 
```

By default, they have the same scope 

![image](https://user-images.githubusercontent.com/18348637/130064246-e730f898-74df-404f-8289-75782d4c3389.png)

![image](https://user-images.githubusercontent.com/18348637/130064272-0a1d9e0d-b8fd-4a23-b5ae-e1f759421bb1.png)

Even thought it is always seems to be recognized in the package:

https://github.com/sublimehq/Packages/blob/8c8a23eb847951e3678dabc840b80116b8854a98/D/D.sublime-syntax#L57

With an extended file i managed to improve it:

```yaml
%YAML 1.2
---
name: D/Custom
file_extensions: [d]
scope: source.d
extends: Packages/D/D.sublime-syntax
contexts:
  type-identifier:
    - meta_prepend: true
    - include: basic
    - include: basic2
  basic:
    - match: '\b({{basic_type}})\b'
      scope: meta.builtin.d
      pop: true
  basic2:
    - match: '\b(size_t)\b'
      scope: meta.builtin.d
      pop: true
```

# Before

![image](https://user-images.githubusercontent.com/18348637/130064515-9274c9c3-0e0f-424a-82d6-5d0829262b4d.png)

# After

![image](https://user-images.githubusercontent.com/18348637/130064555-72c1bb2c-3287-4391-95cc-b751f869cf44.png)

![image](https://user-images.githubusercontent.com/18348637/130064649-02eb7a77-2c17-47be-8e93-a70d53f79bc8.png)
