### ISSUE TITLE
[Ruby/Crystal] Crystal with Ruby like JavaScript with Typescript relationship

### ISSUE THREAD

**Issue by jingyuexing** [sublimehq/Packages#3361]
### What happened?

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
name: Crystal
file_extensions:
  - cr
scope: source.crystal
contexts:
  main:
    - include: Packages/Ruby/Ruby.sublime-syntax#main
```
crystal is static compilable **Ruby** language
