### ISSUE TITLE
Add python as a script language in HTML so that embedded python can be highlighted

### ISSUE THREAD

**Issue by jokoon** [sublimehq/Packages#3485]
### Problem description

Brython allows to embed python code instead of javascript.

With local files, since brython reads files with ajax or another method and since file:/// are not authorized for things other than JS, it's not possible to link local python script, so they must be embedded inside the HTML code.

### Preferred solution

I'm a bit lazy to clone ST and create a PR, so I've edited and uploaded HTML.sublime-syntax (here in .txt format because that's what github allows)

[HTML.sublime-syntax.txt](https://github.com/sublimehq/sublime_text/files/9606114/HTML.sublime-syntax.txt)

### Alternatives

no alternative, as I was advised, this seems like a good solution.

**Comment by jfcherng** [comment]
To add a tl;dr:

Brython allows you to write the following in HTML.

```html
  <script type="text/python">
    //Python codes are here
  </script>
```

**Comment by FichteFoll** [comment]
You can put the following into a `HTML (Brython).sublime-syntax` file in your User package:

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
version: 2
scope: text.html.basic.brython
extends: Packages/HTML/HTML.sublime-syntax

file_extensions:
  - html

contexts:
  script-type-decider:
    - match: (?=(?i:text/python{{unquoted_attribute_break}}|'text/python'|"text/python"))
      set:
        - script-python
        - tag-generic-attribute-meta
        - tag-generic-attribute-value

  script-python:
    - meta_scope: meta.tag.script.begin.html
    - include: script-common
    - match: '>'
      scope: punctuation.definition.tag.end.html
      set: script-python-content

  script-python-content:
    - meta_include_prototype: false
    - match: \s*((<!\[)(CDATA)(\[))
      captures:
        1: meta.tag.sgml.cdata.html
        2: punctuation.definition.tag.begin.html
        3: keyword.declaration.cdata.html
        4: punctuation.definition.tag.begin.html
      pop: 1  # make sure to match only once
      embed: scope:source.python
      embed_scope: meta.tag.sgml.cdata.html source.python.embedded.html
      escape: \]\]>
      escape_captures:
        0: meta.tag.sgml.cdata.html punctuation.definition.tag.end.html
    - match: '{{script_content_begin}}'
      captures:
        1: comment.block.html punctuation.definition.comment.begin.html
      pop: 1  # make sure to match only once
      embed: scope:source.python
      embed_scope: source.python.embedded.html
      escape: '{{script_content_end}}'
      escape_captures:
        1: source.python.embedded.html
        2: comment.block.html punctuation.definition.comment.end.html
        3: source.python.embedded.html
        4: comment.block.html punctuation.definition.comment.end.html
```
