### ISSUE TITLE
[JavaScript] Highlight Class in imports

### ISSUE THREAD

**Issue by 53v3n3d4** [sublimehq/Packages#3676]
### What happened?

Hi,

I was trying to highlight imported Class but I could not achieved.

With this scope `meta.import variable.other.readwrite`, it is possible to highlight all imported methods and classes. But not possible to select only Classes.

I added two matches to achieve highlighting only class

<img width="433" alt="Screenshot 2023-03-10 at 7 02 07 PM" src="https://user-images.githubusercontent.com/115303456/224438363-79273a98-15b2-421b-ae57-81658c4629e3.png">

```yaml
  # JavaScript.sublime-syntax
  # line 319
  import-item:
  ...
    - match: '{{constant_identifier}}'
      scope: variable.other.constant.js
      pop: 1
  ...

  # line 331
   import-brace:
  ...
    - match: '{{constant_identifier}}'
      scope: variable.other.constant.js
      push: import-export-alias

```

Would a pull be welcome? In github we have class highlighting.
