### ISSUE TITLE
[CSS] calc incorrectly scoped as illegal in some circumstances

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#3748]
### What happened?

```css
div {
  --height: 1.5em;
  line-height: var(--height);
  background-image: repeating-linear-gradient(transparent 0 var(--height), green var(--height) calc(var(--height) * 2));
}
```

This is perfectly valid CSS and renders every other line in green. But `calc` isn't scoped as a function, and the `(` is scoped as illegal.
