### ISSUE TITLE
Syntax highlighting engine does NOT exclude & ampersand from set intersections

### ISSUE THREAD

**Issue by eugenesvk** [sublimehq/Packages#3784]
### What happened?

While writing some syntax rules I've discovered that I can't exclude `&` ampersand character when using the very useful `&&` set intersection regex feature, so for a string `A&BCD` the rule `match: '[[ABCD&]&&[^BCD&]]'` excludes `B` `C` and `D`, but not `&`

```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/syntax.html
version: 2
name: syntax
file_extensions:
  - syntax
scope: source.syntax
contexts:
  main:
    - match: '[[ABCD&]&&[^BCD&]]'                          	# fails to exclude &
    # - match: '[[ABCD\x{26}]&&[^BCD\x{26}]]'              	# fails to exclude & once it's got into the inclusion range
    # - match: '[[ABCD\x{25}-\x{28}]&&[^BCD\x{25}-\x{28}]]'	# fails to exclude &
      scope: entity.other.attribute-name
```
