### ISSUE TITLE
[CSS] Support nesting properties directly under at-rules

### ISSUE THREAD

**Issue by nilaallj** [sublimehq/Packages#3820]
### What happened?

When nesting at-rules inside common style rules, syntax highlighting breaks inside the at-rule block unless you start with a new style rule. This is not according to spec since all property declarations applies to the closest ancestor selector, regardless if nested inside an at-rule or not.

Nesting properties like that of course only applies to at-rules that allows it normally, like `@layer`, `@media`, `@container` etc…

See specification: https://www.w3.org/TR/css-nesting-1/#conditionals

```CSS
button {
  @layer defaults {
    /* Syntax highlighting currently doesn’t work for rules nested directly under an at-rule. */
    all: unset;
    offset: revert;
    cursor: pointer;
    padding: 1ex;
    font: inherit;
    line-height: 1cap;
    text-wrap: nowrap;
  }
  @layer components {
    &.report-btn {
      /* Syntax highlighting works as expected when starting a new style rule, even when nested inside an at-rule. */
      color: white;
      background-color: color(display-p3 0.7 0 0);
      border: 2px solid;
      border-radius: 4vmin;
    }
  }
}
```
