### ISSUE TITLE
[CSS] Add highlighting for `@scope` at-rule

### ISSUE THREAD

**Issue by thecodechef** [sublimehq/Packages#3867]
### What happened?

The current CSS.sublime-syntax breaks `@scope` at-rule highlighting

```css
@scope (.light-scheme) {
  a {
    color: red;
  }
}
```
![Screenshot 2023-11-12 at 4 29 08 PM](https://github.com/sublimehq/Packages/assets/5333019/c0352c3d-8d71-4053-8118-753c5e492817)

my current color-scheme & theme are `Bass Blackcomb` & `Treble Adaptive` respectively
