### ISSUE TITLE
[Go] Inline YAML templates not terminated properly before a comment start marker

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#4016]
### What happened?

This is not supposed to be marked as a comment.

```yaml
spec:
  rules:
     - http:
        paths:
          - path: /{{.Values.ingress.path}}/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: 80
```

![image](https://github.com/user-attachments/assets/63c45e33-96ff-42af-9857-a61c88ec0cc5)

Highlighting returns to normal if a space is added before `/*`, but that would obviously be undersirable.
