### ISSUE TITLE
CSS comment bug

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#435]
Please review the image. Sublime is oblivious to the commented line.

![1](https://cloud.githubusercontent.com/assets/1097609/15591229/021ddaae-239c-11e6-8408-ef5fb981b978.png)

So is GitHub apparently.
```CSS
@font-face {
    font-family: Font;
    font-style: normal;
    font-weight: 400;
    src: local(Font),
         /*url(font.woff2) format('woff2'),*/
         url(font.woff) format('woff'),
         url(font.ttf) format('truetype');
}
```
