### ISSUE TITLE
python: last % element in string incorrectly colored

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#489]
This has bothered me for a while now.

![1](https://cloud.githubusercontent.com/assets/1097609/16229662/1c4c5848-37be-11e6-80c3-16cd34c37056.png)

**Comment by keith-hall** [comment]
It's because the `%` before the `M` is captured with the `%H` I think:

    datetime.datetime.utcnow().strftime('%Y%m%d%H%M') # bug
    datetime.datetime.utcnow().strftime('%Y%m%d%H %M') # works
    datetime.datetime.utcnow().strftime('%H %M') # works
    datetime.datetime.utcnow().strftime('%H%M') # bug

**Comment by michaelblyons** [comment]
Interesting. I was tinkering with the string interpolation rules not too long ago. With my test code, only the `%d` is matched since I broke out the `.format()` and string mini-format syntaxes without considering date strings. I tailored the "modes" available to match the doc.

Here's what I had WIP:

```yaml
  constant_placeholder:
    - match: '%(?i:\([a-z_]+\))?#?0?\-? ?\+?([0-9]*|\*)(\.([0-9]*|\*))?[hlL]?[acdeEfFgGiorsuxX%]'
      scope: constant.other.placeholder.python
    - match: '\{([\w.\[\]]*)(.?:[<>=^]?)?[ +-]?\d*(\.\d+)?[bcdeEfFgGnosxX%]?\}'
      scope: constant.other.placeholder.python
```

I could add date formatting strings as an additional set.

------

**Side note:** I originally set out to deal with slightly more complex `.format()` placeholders, but it turns out that they can be nested in ways that aren't exactly simple to parse:

```py
'{0[{1}]}'.format(foo, bar)
'{0:{1}}'.format(foo, bar)
'{0.foo[{0d}]:={1[{2:0>3}]}}'.format(bar, baz, bif)
```
