### ISSUE TITLE
[Scala] Proposal: packages should only be indexed if followed by a scope

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#552]
Scala has two different package syntaxes:

```scala
package fubar

// your stuff here!
```

And this one:

```scala
package fubar {
  // your stuff here
}
```

As of master, sublime currently indexes *both* of these syntaxes.  I think it's basically useless to index the first one, since it's going to appear more or less verbatim at the top of every file (e.g. if you attempt to Cmd-Shift-R "fubar", you're going to get every file in your project).  However, it does seem quite useful to index the *second* version, since this syntax when used generally denotes a package which is only defined in this one place.

**Comment by wbond** [comment]
Sounds reasonable to me

**Comment by wbond** [comment]
Can the `{` be on the following line, or will it always be on the same line as the package name?

**Comment by djspiewak** [comment]
@wbond It can be on the following line, but not two lines ahead.  And idiomatically, I would expect it to only be on the same line.  There's certainly no problem with restricting the indexing to packages which are defined with same-line curlies.

So in other words, this is exactly as easy to implement as you're thinking.  :-)

**Comment by wbond** [comment]
Well, the issue is that the lexer only works on a line-by-line basis, so we can't use a lookahead that spans a linebreak. It won't be hard to create a special sub-scope for a package name without a following `{`, and exclude those from the index. In some cases it won't be correct (if the `{` is on the next line), but unless we change the lexer implementation, that will just have to be how it works.

**Comment by djspiewak** [comment]
Right.  A sub-scope would be the only way to handle following-line stuff, and that would also be capable of handling the "next line, but not the line after it" semantic.  But it's overkill.

Let's just restricted to same line only, just as with lambdas.  Newlines-before-the-brace is a *heavily* discouraged style in Scala for a large number of reasons related to semicolon inference, and it is almost universally avoided.  If you pair that with the fact that most people don't even know about the scoped package construct (which is what we're discussing), I think you get a fairly firm justification of only giving special highlighting to it when on the same line.

```yaml
- match: '\b(package)\s+({{id}})\s*\{'
   captures:
     1: keyword.control.scala
     2: entity.name.namespace.scala
  push: namespace
- match: '\b(package)\s+({{id}})
   captures:
     1: keyword.control.scala
     2: ......stuff??
- match: '\b(package)\b'
   scope: keyword.control.scala

# ...
namespace:
  - meta_scope: meta.namespace.scala
  - match: \}
     pop: true
  - include: main
```

Something like this, I think.
