### ISSUE TITLE
[HTML] Dot in attribute names

### ISSUE THREAD

**Issue by woble** [sublimehq/Packages#575]
Some JS frameworks, i.e. Aurelia, use dots in attribute names, e.g. `<div title.bind="item.title" repeat.for="item for items"></div>`. However Sublime Text HTML syntax doesn't recognize those as attributes, which are valid by [HTML standards](https://www.w3.org/TR/html-markup/syntax.html#attribute-name).

Fix: add `\.` to the regex.

```yaml
        - include: entities

  tag-generic-attribute:
    - match: '\s+(([a-zA-Z0-9:\-_\.]+)\s*(=)\s*)'
      captures:
        1: meta.attribute-with-value.html
        2: entity.other.attribute-name.html
```
