### ISSUE TITLE
CSS: scale-down value of object-fit property missing

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#655]
https://www.w3.org/TR/css3-images/#object-fit

``` CSS
img {
    object-fit: scale-down;
}
```
