### ISSUE TITLE
[CSS] highlighted known font-family part of unknown

### ISSUE THREAD

**Issue by stevenvachon** [sublimehq/Packages#751]
```css
:root {
  --body-font: Raleway, Arial, Helvetica Neue, Helvetica, sans-serif;
}
```

produces:

![screenshot](https://cloud.githubusercontent.com/assets/170197/21429427/aacfcb96-c82c-11e6-8b03-6a5955212144.png)

It probably shouldn't highlight "Helvetica" in "Helvetica Neue".
