### ISSUE TITLE
Syntax Development Tips/Advice

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#757]
If you've spent some time writing syntaxes, take a moment here and share any revelations you've had, or tips on this to test or look for.

**Comment by wbond** [comment]
## Check for Scope Doubling

The characters `(`, `)`, `{`, `}`, `[`, `]` are very easy to double scopes on via `meta_scope`. I try to add tests for `^ punctuation` and then also `^ - punctuation punctuation` to ensure they aren't there.

**Comment by djspiewak** [comment]
# Stateful Chaining

## Don't Over-Use

`sublime-syntax` makes it very easy to have complex interlocking chains of stateful contexts which transition from one to the other via `set`.  This is sometimes necessary to achieve the desired scoping, but it's also very easy to get lost in the mire.  Always convince yourself that you *need* this feature before you use it.

## Push Your First State

While it is absolutely possible to have a `match` in `main` which `set`s into a chain of stateful contexts, and subsequently `set`s back into `main` at the end, it is *not* recommended.  `main` should be a stateless "baseline" context that is always the last element on the stack.  Instead, have your `match` in `main` use `push` to get into your first state, then `pop` out of the last state.  For example, imagine we wanted to match the sequence `abc` with each character scoped differently, and only when they follow each other.  For illustration purposes, we will also match numerics in `main`:

```yaml
contexts:
  main:
    - match: a
      scope: first
      push: expect-b
    - match: \d+
      scope: constant.numeric

  expect-b:
    - match: b
      scope: second
      set: expect-c

  expect-c:
    - match: c
      scope: third
      pop: true
```

Notice how `a` pushes `expect-b`.  We don't `set` the first context, only the second one.  Once we find the terminator, we `pop` out.

### Lookahead Push for Meta-Scoping

Sometimes you need to apply a meta-scope to an entire stateful chunk.  When this is the case, you almost certainly want your `push` rule to be a non-consuming lookahead, rather than a consuming scoped match.  We can modify the above:

```yaml
contexts:
  main:
    - match: (?=a)
      push: expect-a
    - match: \d+
      scope: constant.numeric

  expect-a:
    - meta_scope: meta.abc
    - match: a
      scope: first
      set: expect-b

  expect-b:
    - meta_scope: meta.abc
    - match: b
      scope: second
      set: expect-c

  expect-c:
    - meta_scope: meta.abc
    - match: c
      scope: third
      pop: true
```

## Bail Outs

Always remember that you're writing a parser for a set of *partially* valid syntax fragments.  The normal mode of operation is that someone is actively typing new text.  For this reason, you need to make sure that any and all stateful contexts you use have aggressive "bail-outs" for when something goes wrong.  As a rule of thumb, if there's a case where a compiler's parser would have produced an error, your syntax mode should handle that case by `pop`ing back to `main`.

Consider the example from above.  Imagine the user is typing typing into the following buffer:

```
42
ab
12
```

Even if the user is actively typing `c` following `b`, it would be a terrible experience for the scoping on `12` to shift back and forth as they type in the middle.  For this reason, you should *always* end your mid-state scopes with a lookahead match on `(?=\S)` which pops out of the state chain.  Like so:

```yaml
contexts:
  main:
    - match: (?=a)
      push: expect-a
    - match: \d+
      scope: constant.numeric

  bail-out:
    - match: (?=\S)
      pop: true

  expect-a:
    - meta_scope: meta.abc
    - match: a
      scope: first
      set: expect-b
    - include: bail-out

  expect-b:
    - meta_scope: meta.abc
    - match: b
      scope: second
      set: expect-c
    - include: bail-out

  expect-c:
    - meta_scope: meta.abc
    - match: c
      scope: third
      pop: true
    - include: bail-out
```

Now, when the user starts with the following buffer:

```
42

12
```

They can place the cursor on the second line and type `a` and the scoping on `12` will remain unchanged.  Getting this wrong is one of the easiest ways to create a terrible experience for users of your mode without even realizing it yourself.

# Test Partially-Valid Buffers

Don't just test that correctly-written constructs were scoped appropriately.  Test that partial fragments also scope in a reasonable way.  Test that unrelated constructs which come lexically *after* these partially-valid constructs are also scoped correctly.

**Comment by Thom1729** [comment]
# Use the Stack

Long chains of `set` contexts can be difficult to follow and impossible to understand at a glance. When you have a construction where you expect a list of elements in sequence, put them all onto the stack at once. The stack will unwind as the elements are recognized. Example:

```yaml
contexts:
  else-pop:
    - match: (?=\S)
      pop: true

  function-body:
    - match: \{
      scope: punctuation.section.braces.begin.js
      set:
        - meta-function-body
        - expect-closing-brace
        - statements
        - directives

  meta-function-body:
    - meta_scope: meta.function.body.js
    - include: else-pop

  expect-closing-brace:
    - match: \}
      scope: punctuation.section.braces.end.js
      pop: true
    - include: else-pop

  statements:
    - match: (?=\})
      pop: true

    - ...

  directives:
    - match: "'use (?:strict|asm)';"
      scope: keyword.other.directive.js
    - include: else-pop
```

As an added benefit, most of these scopes can be reused:

```yaml
  statements:
    ...
    - match: \{
      scope: punctuation.section.braces.begin.js
      push:
        - meta-block
        - expect-closing-brace
        - statements
    ...

  meta-block:
    - meta_scope: meta.block.js
    - include: else-pop
```

And they can be easily composed:

```yaml
  expression:
    ...
    - match: \bfunction\b
      scope: meta.function storage.type.function.js
      set:
        - function-body
        - function-parameters // Implementations omitted
        - function-name
    ...
```

As a bonus, states stacked this way are implicitly optional. If one is omitted, the highlighter will move on to the next without interruption. For instance, in the last example, the construction will be parsed correctly whether or not the author supplies a function name.

**Comment by Thom1729** [comment]
# Preprocessing with YAML Macros

Syntax definitions can have a lot of repetitive elements to them. Sometimes, these elements are simple enough that you can simple `include` a utility context:

```yaml
contexts:
  else-pop:
    - match: (?=\S)
      pop: true

  order-expression:
    - match: (?i)\b(?:ASC|DESC|NULLS|FIRST|LAST)\b
      scope: keyword.other.sql
    - include: else-pop
```

But this example contains another common SQL idiom: keywords are always case-insensitive and surrounded by word breaks, so the syntax will contain many repetitions of the `(?i)\b(?:...)\b` pattern. A typo could easily slip into one such repetition. So why write it yourself each time? Instead, use YAML tags and a preprocessor:

```yaml
  order-expression:
    - match: !word ASC|DESC|NULLS|FIRST|LAST
      scope: keyword.other.sql
    - include: else-pop
```

The macro:

```python
# macros.py

def word(match):
    return r'(?i)\b(?:%s)\b' % match
```

The engine:

```python
# build.py

import yaml, sys
from os import path

filename = sys.argv[1]

output_path, extension = path.splitext(path.basename(filename))

if extension != '.source': raise "Not a .source file!"

input_file = open(filename, 'r')
output_file = open(output_path, 'w')

import macros

PREAMBLE = '%YAML 1.2\n---\n'

def apply_transform(loader, node, transform):
    try:
        if isinstance(node, yaml.ScalarNode):
            return transform(loader.construct_scalar(node))
        elif isinstance(node, yaml.SequenceNode):
            return transform(*loader.construct_sequence(node))
        elif isinstance(node, yaml.MappingNode):
            return transform(**loader.construct_mapping(node))
    except TypeError as e:
        print('Failed to transform node: {}\n{}'.format(str(e), node))

def get_constructor(transform):
    return lambda loader, node: apply_transform(loader, node, transform)

for name, transform in macros.__dict__.items():
    if callable(transform):
        yaml.add_constructor(
            '!'+name.lstrip('_'),
            get_constructor(transform)
        )

syntax = yaml.load(input_file)

output_file.write(PREAMBLE)
yaml.dump(syntax, output_file)
```

Another example:

```python
def meta(name):
    return [
        { 'meta_scope': 'meta.%s.sql' % name, },
        { 'match': '', 'pop': True },
    ]
```

```yaml
block:
  - match: !word BEGIN
    scope: keyword.control.sql
    push:
      - !meta block
      - statements
```

We can go further. In Oracle SQL, any identifier may be wrapped in optional double quotes:

```sql
create table mytable ... ;
create table "mytable" ... ;
```

Implementing both versions is possible:

```yaml
  expect-table-name:
    - match: \b{{ident}}\b
      scope: entity.name.table.sql
      pop: true
    - match: (")([^"]+)(")
      captures:
        1: punctuation.definition.string.begin.sql
        2: entity.name.table.sql
        3: punctuation.definition.string.end.sql
      pop: true
    - include: else-pop
```

But then we have to do this for every single type of identifier -- procedure names, aliases, variables, etc. So we write a macro for it:

```python
def expect_identifier(scope):
    return [
        { 'match': r'\b{{ident}}\b', 'scope': scope, 'pop': True },
        {
            'match': r'(")([^"]+)(")',
            'scope': 'string.quoted.double.sql',
            'captures': {
                '1': 'punctuation.definition.string.begin.sql',
                '2': scope,
                '3': 'punctuation.definition.string.end.sql',
            },
            'pop': True,
        },

        { 'match': r'(?=\S)', 'pop': True },
    ]
```

Define all of these scopes the same way:

```yaml
  expect-table-name: !expect_identifier entity.name.table.sql
  expect-alias: !expect_identifier entity.name.alias.sql
```

Or just use the macro inline:

```yaml
declarations:
  ...
  - match: !word TYPE
    scope: storage.type.sql
    push:
      - !meta declaration.type
      - type-definition-value
      - !expect_keyword IS
      - !expect_identifier entity.name.type.sql
  ...
```

Using macros, you can define very complicated constructs in a compact fashion that is easy to understand and reasonably robust against invalid input:

```yaml
- match: !word FOR
  scope: keyword.control.sql
  push:
    - !meta control.for
    - !expect_keyword LOOP
    - !expect_keyword END
    - statements
    - !expect_keyword LOOP
    - expression
    - !expect [ \.\., keyword.operator.other ]
    - expression
    - !expect_keyword REVERSE
    - !expect_keyword IN
    - !expect_identifier variable.other.sql
```

**Comment by tajmone** [comment]
# Unusual Syntaxes and Their Pitfalls

Lately I've started working on a syntax file for an Interactive Fiction (text adventures) programming language which tries to hide the complexity of programming and look like natural English as much as possible. Because of its scarse use of punctuations, I've found myself facing some unexpected problems — the full story here:

- https://forum.sublimetext.com/t/unusual-syntax-help-needed-with-scopes-naming/36354/12
- https://forum.sublimetext.com/t/syntax-definitions-how-to-force-pop-out-of-the-stack/36376/6

Particularly, I was struggling in handling closing block statement of the type `END EVERY identifier.` where both the identifier and the dot terminator where optional. After running in circles for many hours (and due to lack of experience with ST syntaxes), I've managed to achieve it, and would like to share some learned lesson here — they might not be the best solutions, but surely they represent the problem newbies are going to face.

## Forceful Popping

First of all, I faced the problem of how to pop out of the stack in certain (unavoidable) situations. And I was kindly introduced to the `else_POP` technique mentioned earlies in this thread. Still ... the chain of included contexts were not behaving as expected.

The main problem was tied to uncosumed whitespace: the `else_POP` and `immediate_POP` tricks to force your way out of a stacked context can cause a premature pop if there is still some whitespace floating around which isn't captured by the various included contexts. At the end, I had to ensure that the pattern that would `set` the context on the stack would also eat up (and dicard) any trailing whitespace.

Also, another problem was the `END EVERY` construct having two optional trailing keywords (identifier and dot-terminator). To prevent loose scopes floating about, I had to implement an extra check for an `END EVERY` statement followed by only whitespace (ie: neither ID nor terminator).

Here here is the code of how I've managed to workaround the problem:

```yaml
  class:
    - match: (?i)\bEVERY\b
      scope: storage.type.class.alan
      set: [class_body, class_identifier]
  
  class_body:
    - meta_scope: meta.class.alan
    - include: class_head
    - include: class_tail
  class_head:
    - match: (?i)\bIsA\b
      scope: storage.modifier.extends
      push: inherited_class_identifier
    # TODO: inheritance

  class_tail:
    # ===========================
    # END EVERY => no ID & no `.`
    # ===========================
    # When END EVERY is not followed by neither ID or dot, we must capture it
    # separately to avoid stray scopes after it...
    - match: (?i)\b(END\s*EVERY)\b(?=\s*)$
      captures:
        1: keyword.control.alan
      pop: true
    # ==========================
    # END EVERY => ID and/or `.`
    # ==========================
    - match: (?i)\b(END\s*EVERY)\b\s* # <= must consume all whitespace!
      captures:
        1: keyword.control.alan
      set:
        - meta_content_scope: meta.class.alan
        - include: class_tail_identifier
        - include: terminator
        - include: force_POP

  terminator:
    - match: '\.'
      scope: punctuation.terminator.alan
```

It might not be the best solution, but it doesn't have to either: I'm in the early stages of creating this syntax, and sometimes you just need to get the job done and carry on drafting — and things can turn out frustrating when you can't pinpoint what is breaking the expected behavior.

## Watchlist of Common Newbie-Mistakes

The lesson I've learned from tackling with this problem is, which might help better understand which context(s) are causing the problem:

- Always beware of any leftover whitespace from regex match patterns:
    + Try to consume trailing whitespace by capturing it with a discarded group
    + `captures` is better than `scope` because it allows to add extra discarded groups for testing if leading/trailing whitespace is a problem
- Lookaheads are your best friends when it comes to handle optional syntax elements at the end of a `meta` scope
- While working on a syntax's context:
    + Annotate the stack level in side comments (it's so easy to loose track of how deep in the stack each context and included statements are)
    + For reusable syntax-elements contexts, consider creating both a popless version and another one that pops out of the stack (sometimes you might be including them, other times pushing/setting them)
- In lack of context-stack debugger:
    - add some arbitrary label to scopes in order to be able to track in the highlighted code which context is active (when there are variants) — eg: by using `keyword.control.NONE.alan` and `keyword.control.IdOrDOTalan` I was able to uncover the leftover whitespace problem which was causing the wrong context to be used.

I've learned these small lessons the hard way, by running in circles for hours because I wasn't mind-tracking correctly the stack levels. Also, I struggled a lot with `include` vs `push` vs `set` choices, trying to adpat the context to my own likings and pre-existing reusables, which turned out to be a very bad approach.

When starting to deal with lots of reusable contexts, and contexts nestings, it can quickly become a complex task to keep a clear mental picture of what is actually going on at the parser level. Unfortunately, we can't escape the unpleasant task of having to mentally track what RegEx patterns are capturing, consuming, discarding and how the various stacked contexts loop until they pop out. 

Surely, as experience in working with syntaxes starts to set it one eventually develops a right mind frame on how to start out laying the foundations of the syntax with the right foot. The problem is that if the whole experience gets frustrating and no solutions seems possible, one might just give in and never reach that required experience (after all, experience breeds on sucesses, as well as failures).

## A Syntax CLI Simulator/Debugger Would Be Invaluable

Another lesson I've learned:

If ST had a way to expose to the user the syntax parser's stack state, its ques, and some debug info about the text being processed, the regexs matches and failures, it would be much easier to trace where our custom syntaxes fail.

Any chance that (somewhere in the future) ST might also ship with a command line tool to debug syntax definitions? A console app that takes a syntax file and a source test-files as input and spits out two files: a scoped version of the souce file (an XML like doc tree) and a log file listing all the innerworkings of the parser engine. This would be an invaluable tool to both learn how to build syntaxes as well as to fix problems.

Learning to create custom syntaxes should be a pleasant experience, not a frustrating one. The official documentation on the topic is not exactly "exhaustive" (far from it), and most existing syntaxes are usually too large to be used as learning examples to start with.

**Comment by tajmone** [comment]
## Syntax Test Files

[Syntax Test Files] are a great functionality for automating syntax tests. Unfortunately, [ST official documentation on the topic] doesn't cover in depth Scope Selectors. While the examples are all there, I've found the following link to Textmate's documentation quite useful:

- http://manual.macromates.com/en/scope_selectors

Specifically, I've learned more about the syntax for excluding or grouping scope selectors, via documented examples.

### Testing Against Scope Spillings

I've learned how to use syntax files to check that scopes don't spill over to neighbouring elements and/or whitespace.

For example, in this syntax example I'm defining a class in Alan language:

```alan
EVERY cow IsA object.
 -- [some definitions]
END EVERY cow. -- a comment
```

Where everything from `EVERY` to `END EVERY [ID][.]` would be scoped as `meta.class`.

While working on it, I had to deal with scopes that where eating up the trailing whitespace. I've learned to test for those spills using scope selectors subtraction:

```alan
EVERY cow IsA object.
--    ^^^                        meta.class.alan   entity.name.class.alan
--       ^^^^^^^^^^^^            meta.class.alan - entity.name.class.alan
```

The above test-file example snippet checks that the class name scope of `cow` doesn't spill over to the trailing whitespace nor the following elements. The test checks that `cow` is correctly scoped as both `meta.class.alan` and `entity.name.class.alan`, while what follows it (space include) should be scoped as `meta.class.alan` but NOT `entity.name.class.alan` — which is achieved via subtraction (`-`) of the scope.

[Textmate's documentation] on the topic states:

> we can subtract scope selectors to get the (asymmetric) difference using the minus operator.

### Testing Meta Scope Exiting

As a further example, I'll show how to test if the meta scope for the class has been duely exited when expected:

```alan
END EVERY cow. -- a comment
--^^^^^^^^^^^^                                 meta.class.alan
--            ^^^^^^^^^^^^^      source.alan - meta.class.alan
```

Here we're checking that everything up to the terminator dot (included) is scoped as `meta.class.alan`. If the syntax is working correctly, everything following the terminator dot (excluded) should be scoped only as `source.alan` — therefore, we substract from it the meta class scope: `source.alan - meta.class.alan`

Note that you can also test with carets (`^`) beyond the actual contents of the code line being tested:

```alan
END EVERY cow.
--^^^^^^^^^^^^                                 meta.class.alan
--            ^                  source.alan - meta.class.alan
```

... in the above example the `^` is testing a non-existing character beyond the the dot terminator, nevertheless the scope test is correct (you can try to change the test scopes and verify it yourself). This means that it is actually testing that the meta scope effectively end with the `.` terminator.

[Syntax Test Files]: https://www.sublimetext.com/docs/3/syntax.html#testing "Read ST3 official docs on Syntax Test Files"
[ST official documentation on the topic]: https://www.sublimetext.com/docs/3/syntax.html#testing "Read ST3 official docs on Syntax Test Files"

[Textmate's documentation]: http://manual.macromates.com/en/scope_selectors "Read Textmate official docs on Scope Selectors"

**Comment by keith-hall** [comment]
Note that it's mostly pointless to check the "base" scope, unless you're embedding another syntax, so `source.alan - meta.class.alan` can be changed to simply `- meta.class.alan`. Then, one can find that if the meta scopes are tweaked slightly, the negative assertion holds less merit and is harder to identify when it doesn't really prove anything any more - it can be more useful to just check for `- meta.class` or even just `- meta` depending on the circumstances.
And yes, a `^` assertion that points to a character that is after the `\n` on the line being tested just asserts against the `\n` position, i.e. eol.

**Comment by tajmone** [comment]
Thanks for the clarification @keith-hall , I didn't realize you could actually subtract without declaring a base scope. I'll edit the example to clarify this, but at the same time I think is worth leaving in the example also a full `source.alan - meta.class.alan` for learning purposes too,  just to show what is really going on. Unfortunately the documentation of scope selectors is really thin, and most existing syntaxes are uncommented. For example, I've noticed more complex scope selector cases in various color schemes or settings, using groups via parenthesis, but it's not easy to work out how these groups are actually affecting scope selection.

**Comment by keith-hall** [comment]
# Changing Regex Mode in Variables

When declaring variables, don't use `(?x)` to switch to multiline / extended mode, instead wrap it in `(?x:`...`)` to avoid problems where one may expect not to be in extended mode and having to check the variable to know if it changed any options etc. The same applies for ignore case mode as well as any other flags which affect how the regex pattern is parsed.

# Making Variables Atomic
Related to the above, and I'm not sure if this has already been mentioned (I didn't find it with a quick search, but am on mobile and didn't try too hard), but it is also useful to wrap variable declarations in a non-capturing group, so that when referencing them with behavior like `{{example_var}}{2}`, it is unambiguous and doesn't just repeat the last token declared inside that variable.

i.e. `example_var: (?:\w+[.:])` as opposed to `example_var: \w+[.:]`

**Comment by FichteFoll** [comment]
In addition to the suggestion to use `(?x:…)`:

## Use the chomping indicator in block scalars

When using block scalars for your regular expressions, make it a habit to always use `|-` with the hyphen [chomping indicator](https://yaml.org/spec/1.2/spec.html#id2794534) to strip the trailing newline. While whitespaces are ignored in extended mode, in variable definitions where you want to ensure the mode only for the variable, it can be detrimental to add a trailing newline to your variable text.

**Comment by tajmone** [comment]
## Syntax Tests: Use of & Operator in Scopes

While working on syntax tests, I discovered an undocumented feature, i.e. that it's possible to use the `&` operator in the tests scopes. E.g.:

```
// "string"
//<- punctuation.definition.comment.begin & comment.line
```

where without the `&` you'll get an error of umatched scope, because the scopes are in inverted order (i.e. `comment.block` comes first).

I've found this rather useful, especially to keep same scopes aligned with themselves for easy reading the test sources.

I wonder if there are other operators beside `-` and `&` which can be used in syntax tests.

**Comment by FichteFoll** [comment]
Syntax tests work with normal scope selectors and thus [all available operators](https://stackoverflow.com/questions/33562253/sublime-text-scope-selector-operators).

**Comment by rchl** [comment]
## Rule loop processing order within a context

As the documentation states, "When a context has multiple patterns *(rules)*, the leftmost one will be found.". It's also important to add that the rule loop is **reset** when the pattern *(rule)* matches. So with an example context like:

```yaml
line:
- match: 'A'    # 1
  scope: meta.A
- match: 'B'    # 2
  scope: meta.B
```

and line:
```
AB
```

The parser will try rule `#1`, which will match, then will reset the loop and try rule `#1` again. Only then it will progress to rule `#2`. The reason for that is that only rules that consume ZERO characters (either with an explicit empty match like `''`, a lookahead or for example a single `$` or a `^` pattern) advance the rule loop.

So you can't think of rules as being processed unconditionally from top to bottom and assume, for example, that this would allow for matching tokens in a specific order by arranging the rules in a certain way.

## Rule handling around the beginning/end of the line

Once all characters on the line are consumed, and there aren't any more characters to match on that line, the engine will run through the loop once again, matching against a special end-of-line "character". This character can't be explicitly consumed so the only way to get past it is to let the engine go through all the rules for it to be consumed (the rules can still match the end-of-line with patterns like `$` but since those are non-consuming, the rule loop will advance and eventually reach the end).

Example:

```yaml
line:
- match: '$'    # 1
  scope: meta.eol
- match: 'A'    # 2
  scope: meta.A
```

with line:
```
A
```

Engine steps:
 - does not match rule `#1` and advances to rule `#2`
 - matches character `A` with the rule `#2` and reset the loop
 - (optionally goes through the whole loop matching a newline if one exists)
 - matches `EOL` with the rule `#1` and since the match didn't consume anything, advances to rule `#2`
 - does not match rule `#2`
 - the loop ends and if there is another line to match, the engine advances to it
