### ISSUE TITLE
[JavaScript] Division incorrectly highlighted as regex. A general fix is known, but nontrivial and could use feedback.

### ISSUE THREAD

**Issue by Thom1729** [sublimehq/Packages#885]
Examples (note that GitHub gets the second example wrong):

```js
1 /**/ / 2 / /**/ 3;

1
/ 2 /
3;

+function foo () {} /x/i;
```

The root cause seems to be the architecture of `expressions`. The `after-operator` and `after-identifier` contexts work to differentiate uses of the `/` characters in common cases, but they aren't really a general solution. The same architectural issue also holds back #324; the suggested solution there suffers from exactly the same bug.

The third example also suffers from a lack of distinction between statements and expressions.

The general solution I've worked out for this sort of issue is to have separate `expression-head` and `expression-tail` contexts. I've included a minimal example:

```yaml
%YAML 1.2
---
name: Example
scope: source.example

contexts:
  main:
    - match: (?=\S)
      push: [ expression-tail, expression-head ]

  prototype:
    - match: '/\*'
      scope: punctuation.comment.block.begin.example
      push:
        - meta_scope: comment.block.example
        - meta_include_prototype: false
        - match: '\*/'
          scope: punctuation.comment.block.end.example
          pop: true

  expression-tail:
    - match: '/'
      scope: keyword.operator.arithmetic.division.example
      push: expression-head

  expression-head:
    - match: '/'
      scope: punctuation.definition.regex.begin.example
      set:
        - meta_scope: string.regex.example
        - meta_include_prototype: false
        - match: '/'
          scope: punctuation.definition.regex.end.example
          pop: true

    - match: (?=\S)
      pop: true
```

The following are scoped correctly:
```
/abc/ /**/ / /ijk/ / /**/ /xyz/
```

```
/abc/
/ /ijk/ /
/xyz/
```

The `expression-head` context should:

- Match unary prefix operators and continue (do not push, pop, or set).
- Match complete expressions (such as literals or variables) and pop.
- Match opening punctuation (such as `(` or `/`) and set.
- Otherwise, pop.

The `expression-tail` context should:

- Match unary postfix operators and continue.
- Match binary operators and push `expression-head`.
- Otherwise, pop.

As written, this will match one expression and pop everything when the next character is not part of an expression. Slight modification will yield contexts that can parse a list of expressions or gracefully skip invalid input.

---

This might seem like an odd architecture, but I've used it quite a bit (including in an unpublished JavaScript syntax). It should gracefully solve this bug and any similar bugs and allow for an easy solution to #324. I welcome feedback on the approach; if there are no objections, I'll write up a patch.
