### ISSUE TITLE
[CSS] Basic support for jinja2 template engine

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#959]
I am currently working on GitGutter's diff popup. It uses _mdpopups_ to render highlighted code. _mdpopups_ as well as diff popup make use of _jinja2_ template engine to inject some basic logic into the CSS files.

It's absolutely clear to me, that this is nothing one will be faced to in everyday work, but is it possible, to handle jinja2 tags `{% ... %}` and `{{ ... }}` as `comment` or `meta.annotation`?

It's just not to break the whole syntax highlighting, only.

Putting such tags into HTML does not make any harm, but CSS highlighting is breaks by adding such tags.

A quick and dirty hack of the _CSS.sublime-syntax_ would just be enough.

```yaml
  comment-block:
    - match: /\*
      scope: punctuation.definition.comment.css
      push:
        - meta_scope: comment.block.css
        - match: \*/
          scope: punctuation.definition.comment.css
          pop: true
    # Jinja2 control structures (e.g. {% if var.version == 3127 %})
    - match: \{\%
      scope: punctuation.definition.annotation.template.jinja2.css
      push:
        - meta_scope: meta.annotation.template.jinja2.css
        - match: \%\}
          scope: punctuation.definition.annotation.template.jinja2.css
          pop: true
    # Jinja2 replacements (e.g. {{variable_to_add}})
    - match: \{\{
      scope: punctuation.definition.annotation.template.jinja2.css
      push:
        - meta_scope: meta.annotation.template.jinja2.css
        - match: \}\}
          scope: punctuation.definition.annotation.template.jinja2.css
          pop: true
```
